import = ['~/.config/alacritty/themes/themes/catppuccin_mocha.toml']

[env]
TERM = "xterm-256color"

[window]
padding = { x = 0, y = 0 }
# useless when `Fullscreen`
# decorations = "Buttonless"
# opacity = 0.9
# blur = true
startup_mode = "Fullscreen"

[font]
normal.family = 'UbuntuMono Nerd Font Mono' # 'JetBrainsMono Nerd Font' # 'CaskaydiaCove Nerd Font Mono' 
size = 18
offset.y = 4

[[keyboard.bindings]]
key = "Key1"
mods = "Command"
command.program = "/opt/homebrew/bin/tmux"
command.args = ["select-window", "-t", "1"]

[[keyboard.bindings]]
key = "Key2"
mods = "Command"
command.program = "/opt/homebrew/bin/tmux"
command.args = ["select-window", "-t", "2"]

[[keyboard.bindings]]
key = "Key3"
mods = "Command"
command.program = "/opt/homebrew/bin/tmux"
command.args = ["select-window", "-t", "3"]

[[keyboard.bindings]]
key = "Key4"
mods = "Command"
command.program = "/opt/homebrew/bin/tmux"
command.args = ["select-window", "-t", "4"]

[[keyboard.bindings]]
key = "Key5"
mods = "Command"
command.program = "/opt/homebrew/bin/tmux"
command.args = ["select-window", "-t", "5"]
